server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**

        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**,/staffs/**

        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8763/eureka

#okta configuration for api gateway

okta:
  oauth2:
    issuer: https://dev-01607501.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaoforqt6x6zRTQ95d7
    client-secret: tjaG7OJ96rZoLd9KypYUFcASuvDdyY-lGxVizWNfoTm-xHX4Zu5qmZl8xmqcLjBE
    scopes: openid, profile, email, offline_access
